// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuRdrn1cJUTO8w_RodnI6a6wbdih-aaZQ',
    appId: '1:900288138933:web:55ffde7ff63a41071b38fc',
    messagingSenderId: '900288138933',
    projectId: 'woman-clothes-shop',
    authDomain: 'woman-clothes-shop.firebaseapp.com',
    storageBucket: 'woman-clothes-shop.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuRdrn1cJUTO8w_RodnI6a6wbdih-aaZQ',
    appId: '1:900288138933:android:a15ec1988dc21d471b38fc',
    messagingSenderId: '900288138933',
    projectId: 'woman-clothes-shop',
    storageBucket: 'woman-clothes-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuRdrn1cJUTO8w_RodnI6a6wbdih-aaZQ',
    appId: '1:900288138933:ios:a472acd2084953e41b38fc',
    messagingSenderId: '900288138933',
    projectId: 'woman-clothes-shop',
    storageBucket: 'woman-clothes-shop.firebasestorage.app',
    iosBundleId: 'com.example.womenClothShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuRdrn1cJUTO8w_RodnI6a6wbdih-aaZQ',
    appId: '1:900288138933:ios:a472acd2084953e41b38fc',
    messagingSenderId: '900288138933',
    projectId: 'woman-clothes-shop',
    storageBucket: 'woman-clothes-shop.firebasestorage.app',
    iosBundleId: 'com.example.womenClothShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuRdrn1cJUTO8w_RodnI6a6wbdih-aaZQ',
    appId: '1:900288138933:web:55ffde7ff63a41071b38fc',
    messagingSenderId: '900288138933',
    projectId: 'woman-clothes-shop',
    authDomain: 'woman-clothes-shop.firebaseapp.com',
    storageBucket: 'woman-clothes-shop.firebasestorage.app',
  );
}
